config/routes.rb
Strollio::Application.routes.draw do
  resources :contents

  root :to => 'pages#welcome'

  match '/welcome'  => 'pages#welcome',  :as => "welcome",  :via => :get
  match '/about'    => 'pages#about',    :as => "about",    :via => :get
  match '/pictures' => 'pages#pictures', :as => "pictures"
  match '/random'   => 'pages#random',   :as => "random"

  match "auth/:service"          => "auth#service"
  match "auth/:service/callback" => "auth#callback"
  match "logout"                 => "auth#logout"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def callback
    auth = request.env["omniauth.auth"]
    session[:access_token] = auth.credentials.token
    redirect_to root_path
  end

  def logout
    session.clear
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
require 'httparty'

class PagesController < ApplicationController
  def welcome
    @profiles = get_profiles
  end

  def about
    @title = "About"
  end
  
  def pictures
    if session[:access_token].nil?
      flash[:error] = "Oops. You need to sign into a social network first!"
      redirect_to root_path
      return
    end
      
    if params[:q]
      lat_lon_url = "http://where.yahooapis.com/geocode?q=" + URI.escape(params[:q]) + "&appid=" + ENV["YAHOO_APP_ID"]
      @query = HTTParty.get(lat_lon_url).parsed_response
      unless @query["ResultSet"]["Result"].kind_of?(Array)
        begin
          @lat = @query["ResultSet"]["Result"]["latitude"]
          @lon = @query["ResultSet"]["Result"]["longitude"]
        rescue
          flash[:error] = "We're pretty sure that \"#{params[:q]}\" is not a real place."
          redirect_to root_path
          return
        end
        
        @pictures = get_pictures_in
        @additional_pictures = get_additional_pictures(@pictures.count) rescue nil
      end
    else
      flash[:error] = "Oops. You forgot to tell us what to search for."
      redirect_to root_path
      return
    end
    
    if @pictures.blank? and @additional_pictures.blank? and not @query["ResultSet"]["Result"].kind_of?(Array)
      flash[:error] = "Uh oh there aren't any results for \"#{params[:q]}\"."
      redirect_to root_path
      return
    end
  end
  
  def random
    redirect_to pictures_path(:q => Random.rand(100000))
  end
  
  private
  
  def get_profiles
    access_token = session[:access_token]
    url = APP_CONFIG["singly_api_base"] + "/profiles"
    HTTParty.get(url, :query => { :access_token => access_token }).parsed_response if access_token
  end
  
  def get_pictures_in(radius = 10)
    access_token = session[:access_token]
    res = []
    url = APP_CONFIG["singly_api_base"] + "/v0/types/photos_feed"
    query = { :access_token => access_token, :min_count => 1000, :near => "#{@lat},#{@lon}", :dedup => true, :within => radius }
    res += HTTParty.get(url, :query => query ).parsed_response if access_token
    url = APP_CONFIG["singly_api_base"] + "/v0/types/photos"
    res += HTTParty.get(url, :query => query ).parsed_response if access_token
  end
  
  def get_additional_pictures(existing_pics = 0, radius = 10)
    r = radius * 1000
    access_token = session[:access_token]
    url = APP_CONFIG["singly_api_base"] + "/proxy/instagram/media/search"
    res = HTTParty.get(url, :query => { :access_token => access_token, :lat => @lat, :lng => @lon, :distance => r }).parsed_response if access_token
    return res["data"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_alert_type(type)
    case type
    when :alert
      "error"
    when :error
      "error"
    when :notice
      "warning"
    when :success
      "success"
    else
      type.to_s
    end
  end
  
  def title
    base_title = "Stroll.io"
    if @title.nil?
      base_title
    else
      "#{@title} | #{base_title}"
    end
  end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def span_labels(*text)
    res = ""
    text.each do |t|
      res += '<span class="label">' + t + '</span> '
    end
    return (res).html_safe
  end
end

app/views/layouts/_footer.html.erb
<div>
  <p>
    <%= image_tag "https://dev.singly.com/images/singly-text-light.png", :class => "pull-right" %>
  </p>
</div>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32357442-1']);
  _gaq.push(['_setDomainName', 'stroll.io']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Stroll.io", root_path, :class => "brand" %>
      <div class="nav-collapse">
         <%= form_tag pictures_path, :class => "navbar-search", :method => :get do %>
          <%= text_field_tag :q, params[:q], :class => "search-query span5", :placeholder => "Search by zip code, street address, or lat/lon" %>
        <% end %>
        <ul class="nav">

          <li><%= link_to "About", about_path %></li>
          <li>
            <%= link_to random_path do %>
              Surprise
            <% end %>
          </li>
          <li><button id="toggle-fullscreen" rel="Go Fullscreen!" class="btn btn-large btn-primary" data-toggle="button"><i class="icon-resize-full icon-white"></i> Go Full Screen</button></li>
        </ul>
       
        <% if session[:access_token] %>
        <ul class="nav pull-right">
          <li><%= link_to "Sign Out", logout_path %></li>
        </ul>
        <% end %>
      </div><!-- /.nav-collapse -->
    </div>
  </div><!-- /navbar-inner -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "http://blueimp.github.com/JavaScript-Load-Image/load-image.min.js" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= render :partial => 'layouts/google_analytics' %>

</head>
<body>
  
  <%= render :partial => 'layouts/header' %>

  <div class="container">
    <%= render 'shared/flash_messages', :flash => flash %>
    
    <%= yield %>
  </div>
  
  <hr/>
  <div class="container">
    <%= render :partial => 'layouts/footer' %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About stroll.io</h1>
<br>
<div class="row">
  <div class="span9">
    <p>
      You can read all of the guide books in the world, and you'll still ask your friends about their experiences 
      before you decide where to go on vacation. Unfortunately, it's really difficult to browse through the pictures that your friends
      have taken when they were at the sites you're hoping to see.
    </p>
    
    <p>
      As a result you have to facebook stalk all of your friends, which takes a really long time. Since most of us are pretty lazy, we just 
      ask our closest friends to show us their pictures the next time we grab dinner.
    </p>
    
    <p>
      That's all well and good, but odds are you have a lot of friends who you haven't talked to in a while who may have taken photos 
      that will influence your decision. They may even be people you follow on twitter or instagram, that you've never met in real life.
    </p>
    
    <p>
      stroll.io allows you to search through these pictures by geolocation, so you can get a sense of whether or not these 
      are places that you want to visit.
    </p>
    
    <p>
      A picture is a worth a thousand words. We want to make sure that you pick the best place to spend your precious vacations.
    </p>
  </div>
  
  <div class="span3">
    <h3>Find us on Twitter:</h3>
    <h3><%= link_to "@strollioapp", "https://twitter.com/#!/strollioapp" %></h3>
    
    <hr/>
    
    <h3>Find us on <%= link_to "Tumblr", "http://strollio.tumblr.com/" %></h3>
  </div>
</div>

app/views/pages/pictures.html.erb
<h3>You searched for "<%= params[:q] %>"</h3>

<% if @query["ResultSet"]["Result"].kind_of?(Array) %>
<h4>Uh oh. That's not specific enough. Which location did you mean to search for?</h4>
<br>
<ul>
  <% @query["ResultSet"]["Result"].each do |addr| %>
  <li>
    <% loc = [addr["city"], addr["county"], addr["state"], addr["country"]].compact.join(", ") %>
    <%= link_to loc, pictures_path(:q => loc) %>
  </li>
  <% end %>
</ul>
<% else %>
<h4>
  We searched around
  <% addr = @query["ResultSet"]["Result"] %> 
  "<%= [addr["city"], addr["county"], addr["state"], addr["country"]].compact.join(", ") %>"
  &mdash;
  <%= link_to "Book a flight here with Hipmunk!", "http://www.hipmunk.com" %>
</h4>
<% end %>
<br>


<hr>

<!--STATIC IMAGE GALLERY -->

<div class="row">
  <div class="span12">

    <div id="gallery" data-toggle="modal-gallery" data-target="#modal-gallery">
      <h2 class="bold"> Your Network </h2>
      <% if @pictures %>      
        <% @pictures.each do |p| %>
          <% caption = p["data"]["caption"] %>
          <% if caption %>
            <% title = [] %>
            <% title << (caption["from"]["username"]).html_safe rescue nil %>
            <% title << caption["text"] rescue nil %>
            <% title = title.join(" &mdash; ").html_safe %>
          <% else %>
            <% title = [] %>
            <% title << p["data"]["from"]["name"] rescue nil %>
            <% title << p["data"]["name"] rescue nil %>
            <% title = title.join(" &mdash; ").html_safe %>
          <% end %>

          <%= link_to p["oembed"]["url"], :title => title, :rel => "gallery" do %>
            <div class="thumb-container">
              <%= image_tag p["oembed"]["url"], :class => "thumb" %>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <h3>Nothin!</h3>
      <% end %>

      <hr>
      <h2 class="bold"> The Web</h2>
      <% if @additional_pictures %>
        <% @additional_pictures.each do |p| %>
          <% caption = p["caption"] %>
          <% if caption %>
            <% title = [] %>
            <% title << (caption["from"]["username"]).html_safe rescue nil %>
            <% title << caption["text"] rescue nil %>
            <% title = title.join(" &mdash; ").html_safe %>
          <% end %>

          <%= link_to p["images"]["standard_resolution"]["url"], :title => title, :rel => "gallery" do %>
            <div class="thumb-container">
              <%= image_tag p["images"]["standard_resolution"]["url"], :class => "thumb" %>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <h3>Nothin!</h3>
      <% end %>
    </div>
  </div>

<!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
    <h3 class="modal-title"></h3>
  </div>
  <div class="modal-body"><div class="modal-image"></div></div>
</div>

app/views/pages/welcome.html.erb
<center>
<header style="margin-bottom: 20px;" class="jumbotron masthead">
  <div class="inner">
    <h1>Welcome!</h1>
    <p>Search and stroll through photos from your network and the web.</p>
    <hr style="border-top: 1px solid #333;">
    <p style="width: 600px; line-height: 24px; font-size: 20px;">Connect your social accounts below to see your photos (and your friends' photos) for any given location.</p>
  </div>
</header>
<div style="width: 550px; line-height: 10px; background-color: #fff; box-shadow: inset 1px 1px 2px #666;" class="well">
  
  <% %w[instagram foursquare twitter facebook].each do |service| %>
  <div class="row">
  <ul class="services">
    <li class="service-name">
      <%= service.capitalize %>
      <% if @profiles && @profiles[service] %>
        <div class="service-is-connected">
          is connected
          <% @profiles[service] %>
        </div>
      <% else %>
        <div class="service-not-connected">
        <%= link_to "Connect", "/auth/singly?service=#{service}", :class => 'btn btn-primary' %>
      </div>
      <% end %>
    </li>
  </ul>
</div>
  <% end %>
</div>
</center>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <h4>
      <%= pluralize(object.errors.count, "error")%>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:
    </h4>
    <ul>
    <% object.errors.full_messages.each do |m| %>
      <li><i><%= m %></i></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-block alert-<%= bootstrap_alert_type(type) %>">
    <a class="close" data-dismiss="alert" href="#">&times</a>
    <%= message %>
  </div>
<% end %>